module.exports = {
  'extends': [
    'eslint:recommended',
    'prettier',
  ],
  'plugins': [
    'spellcheck'
  ],
  'parser': 'babel-eslint',
  'parserOptions': {
    'ecmaVersion': 2018,
  },
  'env': {
    'es6': true,
  },
  'rules': {
    'no-console': ['error', { 'allow': ['warn', 'error'] }],

    // Best Practices
    'curly': 'error',
    'eqeqeq': 'error',
    'no-eq-null': 'error',

    // Variables
    'no-use-before-define': ['error', 'nofunc'],

    // Stylistic Issues
    'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': 'error',
    'comma-style': 'error',
    'func-call-spacing': 'error',
    'indent': ['error', 2, { 'SwitchCase': 1, 'MemberExpression': 1 }],
    'key-spacing': ['error', { 'mode': 'minimum' }],
    'keyword-spacing': 'error',
    'object-curly-spacing': ['error', 'always'],
    'one-var': ['error', 'never'],
    'quotes': ['error', 'single', { 'allowTemplateLiterals': true }],
    'semi': ['error', 'always'],
    'space-before-function-paren': ['error', {
      'anonymous': 'never',
      'named': 'never',
      'asyncArrow': 'always'
    }],
    'space-infix-ops': 'error',

    // ECMAScript 6
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'as-needed'],
    'arrow-spacing': 'error',
    'no-duplicate-imports': 'error',
    'no-useless-constructor': 'error',
    'no-var': 'error',
    'prefer-const': 'error',
    'prefer-template': 'error',

    // Spellcheck
    'spellcheck/spell-checker': ['error', {
      'comments': true,
      'strings': true,
      'identifiers': true,
      'lang': 'en_GB',
      'skipWords': [
        // Node package names
        'eslint',
        'gatsby',
        'github',

        // File extensions
        'css',
        'html',
        'js',
        'json',
        'md',
        'png',
        'svg',
        'xml',

        // American English
        'color',
        'center',

        // Fonts
        'helvetica',
        'roboto',
        'neue',
        'segoe',

        // Programming gibberish
        'addon',
        'addons',
        'alt',
        'antialiased',
        'api',
        'arg',
        'args',
        'asc',
        'async',
        'atan',
        'attr',
        'attrs',
        'auth',
        'autocomplete',
        'autoincrement',
        'backend',
        'basename',
        'bcrypt',
        "bezier",
        "bool",
        'broadcasted',
        'chainable',
        'cli',
        'clickability',
        'concat',
        'conf',
        'config',
        'configs',
        'const',
        'ctrl',
        'customizer',
        'deregister',
        'deregistered',
        'deregistering',
        'deregistrator',
        'deregistrators',
        'desc',
        'deserialization',
        'deserialize',
        'deserialized',
        'deserializes',
        'dest',
        'destructuring',
        'dev',
        'dict',
        'dir',
        'dirname',
        'div',
        'dom',
        'dragend',
        'dragstart',
        'el',
        'elem',
        'elems',
        'env',
        'envs',
        'err',
        'falsy',
        'filename',
        'fn',
        'fns',
        'formatters',
        'fulfillable',
        'fullscreen',
        'func',
        'getter',
        'gql',
        'graphql',
        'grayscale',
        'hostname',
        'http',
        'https',
        'img',
        'init',
        'initializer',
        'injectable',
        'instantiation',
        'iso',
        'iterable',
        'iteree',
        'jsx',
        "keydown",
        "keyup",
        'laquo',
        'lib',
        'libs',
        'lifecycle',
        'linter',
        'linters',
        'metadata',
        'middleware',
        'minified',
        'mixin',
        'mixins',
        'moz',
        'multiselect',
        'nav',
        'noop',
        'osx',
        'param',
        'params',
        'parsers',
        'plugins',
        'polyfill',
        'polyfilled',
        'polyfills',
        'popup',
        'prefetch',
        'preload',
        'preloaded',
        'preprocess',
        'preprocessor',
        'preprocessors',
        'preselected',
        'programmatically',
        'proto',
        'px',
        'raquo',
        'readdir',
        'reconfiguring',
        'refetch',
        'refetching',
        'resolvers',
        'ret',
        'rethrows',
        'rgba',
        'runtime',
        'sanitization',
        'serialize',
        'serializer',
        'sha',
        'shorthands',
        'sourcemap',
        'sourcemaps',
        'sqrt',
        'src',
        'stderr',
        'stdin',
        'stdout',
        'stacktrace',
        'subdirectories',
        'subdirectory',
        'subunit',
        'subunits',
        'superset',
        'thanables',
        'thenable',
        'timeline',
        'timestamp',
        'tmp',
        'todo',
        'truthy',
        'typedef',
        'ui',
        'uncomment',
        'unfulfillable',
        'ungroup',
        'ungrouped',
        'unhandled',
        'uniq',
        'unwatch',
        'uri',
        'utc',
        'util',
        'utils',
        'uuid',
        'validator',
        'viewport',
        'vh',
        'vw',
        'webkit',
        'webpack',
        'webserver',
        'whitelist',
        'whitelisted',
        'www',
        'xxl',
        'xxs',
        'zindex',

        // Libraries
        'stringify',  // in JSON.stringify
        'substr', // in String#substr
        'unshift', // in Array#unshift
      ],
      'skipIfMatch': [
        // Web addresses
        'http(s)?://[^s]*',
        // Email addresses
        '^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$',
        // Twitter handle
        '^@?(\w){1,15}$',
        // SVG data attribute
        'd\=\"([MLQTCSAZVH])([^MLQTCSAZVH]*)\"',
        // Hex colours
        '^#[0-9a-f]{3,6}$',
      ],
      'minLength': 3,
    }],
  }
};
